### ISSUE TITLE
Error trying run demo

### ISSUE THREAD

**Issue by amgtel** [nucypher/vehicle-data-exchange#2]
When I install dependencies with ($pipenv install --dev --three --skip-lock --pre) I get  errors:

> nics@nics-virtual-machine:~/nucypher/vehicle-data-exchange$ pipenv install --dev --three --skip-lock --pre
> Creating a virtualenv for this project…
> Pipfile: /home/nics/nucypher/vehicle-data-exchange/Pipfile
> Using /usr/local/bin/python3.8 (3.8.3) to create virtualenv…
> ⠋ Creating virtual environment...created virtual environment CPython3.8.3.final.0-64 in 4439ms
>   creator CPython3Posix(dest=/home/nics/.local/share/virtualenvs/vehicle-data-exchange-cEJPwm8i, clear=False, global=False)
>   seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/nics/.local/share/virtualenv/seed-app-data/v1.0.1)
>   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
> 
> ✔ Successfully created virtual environment! 
> Virtualenv location: /home/nics/.local/share/virtualenvs/vehicle-data-exchange-cEJPwm8i
> Installing dependencies from Pipfile…
> An error occurred while installing dash-core-components==0.41.0! Will try again.
> An error occurred while installing -e git+https://github.com/cygnusv/nucypher.git@fix-demo#egg=nucypher! Will try again.
>   🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 10/10 — 00:05:28
> Installing initially failed dependencies…
> [InstallError]:   File "/home/nics/.local/lib/python3.7/site-packages/pipenv/cli/command.py", line 252, in install
> [InstallError]:       site_packages=state.site_packages
> [InstallError]:   File "/home/nics/.local/lib/python3.7/site-packages/pipenv/core.py", line 2062, in do_install
> [InstallError]:       keep_outdated=keep_outdated
> [InstallError]:   File "/home/nics/.local/lib/python3.7/site-packages/pipenv/core.py", line 1314, in do_init
> [InstallError]:       pypi_mirror=pypi_mirror,
> [InstallError]:   File "/home/nics/.local/lib/python3.7/site-packages/pipenv/core.py", line 901, in do_install_dependencies
> [InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
> [InstallError]:   File "/home/nics/.local/lib/python3.7/site-packages/pipenv/core.py", line 796, in batch_install
> [InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
> [InstallError]:   File "/home/nics/.local/lib/python3.7/site-packages/pipenv/core.py", line 703, in _cleanup_procs
> [InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
> [pipenv.exceptions.InstallError]: Obtaining nucypher from git+https://github.com/cygnusv/nucypher.git@fix-demo#egg=nucypher (from -r /tmp/pipenv-8cpqyqws-requirements/pipenv-laa47jua-requirement.txt (line 1))
> [pipenv.exceptions.InstallError]:   Updating /home/nics/.local/share/virtualenvs/vehicle-data-exchange-cEJPwm8i/src/nucypher clone (to revision fix-demo)
> [pipenv.exceptions.InstallError]: Collecting appdirs==1.4.3
> [pipenv.exceptions.InstallError]:   Using cached appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
> [pipenv.exceptions.InstallError]: Collecting argh==0.26.2
> [pipenv.exceptions.InstallError]:   Using cached argh-0.26.2-py2.py3-none-any.whl (30 kB)
> [pipenv.exceptions.InstallError]: Collecting asn1crypto==0.24.0
> [pipenv.exceptions.InstallError]:   Using cached asn1crypto-0.24.0-py2.py3-none-any.whl (101 kB)
> [pipenv.exceptions.InstallError]: Collecting attrdict==2.0.1
> [pipenv.exceptions.InstallError]:   Using cached attrdict-2.0.1-py2.py3-none-any.whl (9.9 kB)
> [pipenv.exceptions.InstallError]: Collecting attrs==18.2.0
> [pipenv.exceptions.InstallError]:   Using cached attrs-18.2.0-py2.py3-none-any.whl (34 kB)
> [pipenv.exceptions.InstallError]: Collecting autobahn==19.1.1
> [pipenv.exceptions.InstallError]:   Using cached autobahn-19.1.1-py2.py3-none-any.whl (302 kB)
> [pipenv.exceptions.InstallError]: Collecting automat==0.7.0
> [pipenv.exceptions.InstallError]:   Using cached Automat-0.7.0-py2.py3-none-any.whl (37 kB)
> [pipenv.exceptions.InstallError]: Collecting boto3==1.9.91
> [pipenv.exceptions.InstallError]:   Using cached boto3-1.9.91-py2.py3-none-any.whl (128 kB)
> [pipenv.exceptions.InstallError]: Collecting botocore==1.12.91
> [pipenv.exceptions.InstallError]:   Using cached botocore-1.12.91-py2.py3-none-any.whl (5.3 MB)
> [pipenv.exceptions.InstallError]: Collecting bytestring-splitter==1.0.0a4
> [pipenv.exceptions.InstallError]:   Using cached bytestring_splitter-1.0.0a4-py3-none-any.whl (9.9 kB)
> [pipenv.exceptions.InstallError]: Collecting certifi==2018.11.29
> [pipenv.exceptions.InstallError]:   Using cached certifi-2018.11.29-py2.py3-none-any.whl (154 kB)
> [pipenv.exceptions.InstallError]: Collecting cffi==1.11.5
> [pipenv.exceptions.InstallError]:   Using cached cffi-1.11.5.tar.gz (438 kB)
> [pipenv.exceptions.InstallError]: Requirement already satisfied, skipping upgrade: chardet==3.0.4 in /home/nics/.local/share/virtualenvs/vehicle-data-exchange-cEJPwm8i/lib/python3.8/site-packages (from nucypher->-r /tmp/pipenv-8cpqyqws-requirements/pipenv-laa47jua-requirement.txt (line 1)) (3.0.4)
> [pipenv.exceptions.InstallError]: Collecting click==7.0
> [pipenv.exceptions.InstallError]:   Using cached Click-7.0-py2.py3-none-any.whl (81 kB)
> [pipenv.exceptions.InstallError]: Collecting colorama==0.4.1
> [pipenv.exceptions.InstallError]:   Using cached colorama-0.4.1-py2.py3-none-any.whl (15 kB)
> [pipenv.exceptions.InstallError]: Collecting constant-sorrow==0.1.0a8
> [pipenv.exceptions.InstallError]:   Using cached constant_sorrow-0.1.0a8-py3-none-any.whl (12 kB)
> [pipenv.exceptions.InstallError]: Collecting constantly==15.1.0
> [pipenv.exceptions.InstallError]:   Using cached constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
> [pipenv.exceptions.InstallError]: Collecting cryptography==2.5
> [pipenv.exceptions.InstallError]:   Using cached cryptography-2.5-cp34-abi3-manylinux1_x86_64.whl (2.4 MB)
> [pipenv.exceptions.InstallError]: Collecting dateparser==0.7.0
> [pipenv.exceptions.InstallError]:   Using cached dateparser-0.7.0-py2.py3-none-any.whl (357 kB)
> [pipenv.exceptions.InstallError]: Collecting docutils==0.14
> [pipenv.exceptions.InstallError]:   Using cached docutils-0.14-py3-none-any.whl (543 kB)
> [pipenv.exceptions.InstallError]: Collecting eth-abi==2.0.0b5
> [pipenv.exceptions.InstallError]:   Using cached eth_abi-2.0.0b5-py3-none-any.whl (24 kB)
> [pipenv.exceptions.InstallError]: Collecting eth-account==0.3.0
> [pipenv.exceptions.InstallError]:   Using cached eth_account-0.3.0-py3-none-any.whl (18 kB)
> [pipenv.exceptions.InstallError]: Collecting eth-bloom==1.0.3
> [pipenv.exceptions.InstallError]:   Using cached eth_bloom-1.0.3-py3-none-any.whl (5.4 kB)
> [pipenv.exceptions.InstallError]: Collecting eth-hash[pycryptodome,pysha3]==0.2.0
> [pipenv.exceptions.InstallError]:   Using cached eth_hash-0.2.0-py3-none-any.whl (7.2 kB)
> [pipenv.exceptions.InstallError]: Collecting eth-keyfile==0.5.1
> [pipenv.exceptions.InstallError]:   Using cached eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
> [pipenv.exceptions.InstallError]: Collecting eth-keys==0.2.1
> [pipenv.exceptions.InstallError]:   Using cached eth_keys-0.2.1-py3-none-any.whl (17 kB)
> [pipenv.exceptions.InstallError]: Collecting eth-rlp==0.1.2
> [pipenv.exceptions.InstallError]:   Using cached eth_rlp-0.1.2-py3-none-any.whl (6.5 kB)
> [pipenv.exceptions.InstallError]: Collecting eth-tester==0.1.0b37
> [pipenv.exceptions.InstallError]:   Using cached eth_tester-0.1.0b37-py3-none-any.whl (58 kB)
> [pipenv.exceptions.InstallError]: Collecting eth-typing==2.0.0
> [pipenv.exceptions.InstallError]:   Using cached eth_typing-2.0.0-py3-none-any.whl (4.6 kB)
> [pipenv.exceptions.InstallError]: Collecting eth-utils==1.4.1
> [pipenv.exceptions.InstallError]:   Using cached eth_utils-1.4.1-py3-none-any.whl (17 kB)
> [pipenv.exceptions.InstallError]: Collecting flask==1.0.2
> [pipenv.exceptions.InstallError]:   Using cached Flask-1.0.2-py2.py3-none-any.whl (91 kB)
> [pipenv.exceptions.InstallError]: Collecting hendrix==3.2.2
> [pipenv.exceptions.InstallError]:   Using cached hendrix-3.2.2-py3-none-any.whl (55 kB)
> [pipenv.exceptions.InstallError]: Collecting hexbytes==0.1.0
> [pipenv.exceptions.InstallError]:   Using cached hexbytes-0.1.0-py3-none-any.whl (6.8 kB)
> [pipenv.exceptions.InstallError]: Collecting humanize==0.5.1
> [pipenv.exceptions.InstallError]:   Using cached humanize-0.5.1.tar.gz (14 kB)
> [pipenv.exceptions.InstallError]: Collecting hyperlink==18.0.0
> [pipenv.exceptions.InstallError]:   Using cached hyperlink-18.0.0-py2.py3-none-any.whl (37 kB)
> [pipenv.exceptions.InstallError]: Collecting idna==2.8
> [pipenv.exceptions.InstallError]:   Using cached idna-2.8-py2.py3-none-any.whl (58 kB)
> [pipenv.exceptions.InstallError]: Collecting incremental==17.5.0
> [pipenv.exceptions.InstallError]:   Using cached incremental-17.5.0-py2.py3-none-any.whl (16 kB)
> [pipenv.exceptions.InstallError]: Collecting ipfsapi==0.4.3
> [pipenv.exceptions.InstallError]:   Using cached ipfsapi-0.4.3-py2.py3-none-any.whl (142 kB)
> [pipenv.exceptions.InstallError]: Requirement already satisfied, skipping upgrade: itsdangerous==1.1.0 in /home/nics/.local/share/virtualenvs/vehicle-data-exchange-cEJPwm8i/lib/python3.8/site-packages (from nucypher->-r /tmp/pipenv-8cpqyqws-requirements/pipenv-laa47jua-requirement.txt (line 1)) (1.1.0)
> [pipenv.exceptions.InstallError]: Collecting jinja2==2.10
> [pipenv.exceptions.InstallError]:   Using cached Jinja2-2.10-py2.py3-none-any.whl (126 kB)
> [pipenv.exceptions.InstallError]: Collecting jmespath==0.9.3
> [pipenv.exceptions.InstallError]:   Using cached jmespath-0.9.3-py2.py3-none-any.whl (23 kB)
> [pipenv.exceptions.InstallError]: Collecting jsonschema==2.6.0
> [pipenv.exceptions.InstallError]:   Using cached jsonschema-2.6.0-py2.py3-none-any.whl (39 kB)
> [pipenv.exceptions.InstallError]: Processing /home/nics/.cache/pipenv/wheels/c6/91/94/23d462effc91bc844998b2023dc2dfd037a9d0a60034ddab16/lru_dict-1.1.6-cp38-cp38-linux_x86_64.whl
> [pipenv.exceptions.InstallError]: Collecting markupsafe==1.1.0
> [pipenv.exceptions.InstallError]:   Using cached MarkupSafe-1.1.0.tar.gz (18 kB)
> [pipenv.exceptions.InstallError]: Collecting maya==0.6.1
> [pipenv.exceptions.InstallError]:   Using cached maya-0.6.1-py2.py3-none-any.whl (12 kB)
> [pipenv.exceptions.InstallError]: Requirement already satisfied, skipping upgrade: msgpack-python==0.5.6 in /home/nics/.local/share/virtualenvs/vehicle-data-exchange-cEJPwm8i/lib/python3.8/site-packages (from nucypher->-r /tmp/pipenv-8cpqyqws-requirements/pipenv-laa47jua-requirement.txt (line 1)) (0.5.6)
> [pipenv.exceptions.InstallError]: Collecting mypy-extensions==0.4.1
> [pipenv.exceptions.InstallError]:   Using cached mypy_extensions-0.4.1-py2.py3-none-any.whl (3.6 kB)
> [pipenv.exceptions.InstallError]: Processing /home/nics/.cache/pipenv/wheels/d8/af/19/fb896f509a437aca2dcf62583e84d7fb2cd5b628c1564a609c/parsimonious-0.8.1-py3-none-any.whl
> [pipenv.exceptions.InstallError]: Processing /home/nics/.cache/pipenv/wheels/4c/8e/7e/72fbc243e1aeecae64a96875432e70d4e92f3d2d18123be004/pathtools-0.1.2-py3-none-any.whl
> [pipenv.exceptions.InstallError]: Collecting pendulum==2.0.4
> [pipenv.exceptions.InstallError]:   Using cached pendulum-2.0.4.tar.gz (75 kB)
> [pipenv.exceptions.InstallError]:   Installing build dependencies: started
> [pipenv.exceptions.InstallError]:   Installing build dependencies: finished with status 'done'
> [pipenv.exceptions.InstallError]:   Getting requirements to build wheel: started
> [pipenv.exceptions.InstallError]:   Getting requirements to build wheel: finished with status 'done'
> [pipenv.exceptions.InstallError]:     Preparing wheel metadata: started
> [pipenv.exceptions.InstallError]:     Preparing wheel metadata: finished with status 'done'
> [pipenv.exceptions.InstallError]: Collecting protobuf==3.7.0rc2
> [pipenv.exceptions.InstallError]:   Using cached protobuf-3.7.0rc2-py2.py3-none-any.whl (404 kB)
> [pipenv.exceptions.InstallError]: Collecting py-ecc==1.4.7
> [pipenv.exceptions.InstallError]:   Using cached py_ecc-1.4.7-py3-none-any.whl (29 kB)
> [pipenv.exceptions.InstallError]: Collecting py-evm==0.2.0a39
> [pipenv.exceptions.InstallError]:   Using cached py_evm-0.2.0a39-py3-none-any.whl (219 kB)
> [pipenv.exceptions.InstallError]: Collecting py-geth==2.0.1
> [pipenv.exceptions.InstallError]:   Using cached py_geth-2.0.1-py3-none-any.whl (20 kB)
> [pipenv.exceptions.InstallError]: Collecting pyasn1-modules==0.2.4
> [pipenv.exceptions.InstallError]:   Using cached pyasn1_modules-0.2.4-py2.py3-none-any.whl (66 kB)
> [pipenv.exceptions.InstallError]: Collecting pyasn1==0.4.5
> [pipenv.exceptions.InstallError]:   Using cached pyasn1-0.4.5-py2.py3-none-any.whl (73 kB)
> [pipenv.exceptions.InstallError]: Processing /home/nics/.cache/pipenv/wheels/67/07/a1/ecdb81a78a830585c903743a8452d4632e541f609b134b3cba/pychalk-2.0.1-py3-none-any.whl
> [pipenv.exceptions.InstallError]: Collecting pycparser==2.19
> [pipenv.exceptions.InstallError]:   Using cached pycparser-2.19.tar.gz (158 kB)
> [pipenv.exceptions.InstallError]: Collecting pycryptodome==3.7.3
> [pipenv.exceptions.InstallError]:   Using cached pycryptodome-3.7.3.tar.gz (9.3 MB)
> [pipenv.exceptions.InstallError]: Processing /home/nics/.cache/pipenv/wheels/5b/31/89/0b592e364dd6f1d8764e15e2cfb046320cae7f387200a00bc6/pyethash-0.1.27-cp38-cp38-linux_x86_64.whl
> [pipenv.exceptions.InstallError]: Collecting pyhamcrest==1.9.0
> [pipenv.exceptions.InstallError]:   Using cached PyHamcrest-1.9.0-py2.py3-none-any.whl (52 kB)
> [pipenv.exceptions.InstallError]: Collecting pynacl==1.3.0
> [pipenv.exceptions.InstallError]:   Using cached PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_64.whl (759 kB)
> [pipenv.exceptions.InstallError]: Collecting pyopenssl==19.0.0
> [pipenv.exceptions.InstallError]:   Using cached pyOpenSSL-19.0.0-py2.py3-none-any.whl (53 kB)
> [pipenv.exceptions.InstallError]: Requirement already satisfied, skipping upgrade: pysha3==1.0.2 in /home/nics/.local/share/virtualenvs/vehicle-data-exchange-cEJPwm8i/lib/python3.8/site-packages (from nucypher->-r /tmp/pipenv-8cpqyqws-requirements/pipenv-laa47jua-requirement.txt (line 1)) (1.0.2)
> [pipenv.exceptions.InstallError]: Collecting pytest-ethereum==0.1.3a6
> [pipenv.exceptions.InstallError]:   Using cached pytest_ethereum-0.1.3a6-py3-none-any.whl (11 kB)
> [pipenv.exceptions.InstallError]: Collecting pytz==2018.9
> [pipenv.exceptions.InstallError]:   Using cached pytz-2018.9-py2.py3-none-any.whl (510 kB)
> [pipenv.exceptions.InstallError]: Collecting pytzdata==2018.9
> [pipenv.exceptions.InstallError]:   Using cached pytzdata-2018.9-py2.py3-none-any.whl (981 kB)
> [pipenv.exceptions.InstallError]: Collecting pyyaml==4.2b4
> [pipenv.exceptions.InstallError]:   Using cached PyYAML-4.2b4.tar.gz (262 kB)
> [pipenv.exceptions.InstallError]: Collecting regex==2019.2.7
> [pipenv.exceptions.InstallError]:   Using cached regex-2019.02.07.tar.gz (643 kB)
> [pipenv.exceptions.InstallError]: Collecting requests==2.21.0
> [pipenv.exceptions.InstallError]:   Using cached requests-2.21.0-py2.py3-none-any.whl (57 kB)
> [pipenv.exceptions.InstallError]: Collecting rlp==1.1.0
> [pipenv.exceptions.InstallError]:   Using cached rlp-1.1.0-py2.py3-none-any.whl (18 kB)
> [pipenv.exceptions.InstallError]: Collecting s3transfer==0.2.0
> [pipenv.exceptions.InstallError]:   Using cached s3transfer-0.2.0-py2.py3-none-any.whl (69 kB)
> [pipenv.exceptions.InstallError]: Collecting semantic-version==2.6.0
> [pipenv.exceptions.InstallError]:   Using cached semantic_version-2.6.0-py3-none-any.whl (14 kB)
> [pipenv.exceptions.InstallError]: Collecting sentry-sdk==0.5.2
> [pipenv.exceptions.InstallError]:   Using cached sentry_sdk-0.5.2-py2.py3-none-any.whl (43 kB)
> [pipenv.exceptions.InstallError]: Collecting service-identity==18.1.0
> [pipenv.exceptions.InstallError]:   Using cached service_identity-18.1.0-py2.py3-none-any.whl (11 kB)
> [pipenv.exceptions.InstallError]: Collecting six==1.12.0
> [pipenv.exceptions.InstallError]:   Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
> [pipenv.exceptions.InstallError]: Processing /home/nics/.cache/pipenv/wheels/ef/75/ba/deb00489e86fe8ed045887958363a3ddf664227d0bab7f03a2/snaptime-0.2.4-py3-none-any.whl
> [pipenv.exceptions.InstallError]: Collecting sqlalchemy==1.3.0b3
> [pipenv.exceptions.InstallError]:   Using cached SQLAlchemy-1.3.0b3.tar.gz (5.8 MB)
> [pipenv.exceptions.InstallError]: Collecting toolz==0.9.0
> [pipenv.exceptions.InstallError]:   Using cached toolz-0.9.0.tar.gz (45 kB)
> [pipenv.exceptions.InstallError]: Collecting trie==1.3.8
> [pipenv.exceptions.InstallError]:   Using cached trie-1.3.8-py3-none-any.whl (19 kB)
> [pipenv.exceptions.InstallError]: Collecting twisted==18.9.0
> [pipenv.exceptions.InstallError]:   Using cached Twisted-18.9.0.tar.bz2 (3.1 MB)
> [pipenv.exceptions.InstallError]: Collecting txaio==18.8.1
> [pipenv.exceptions.InstallError]:   Using cached txaio-18.8.1-py2.py3-none-any.whl (27 kB)
> [pipenv.exceptions.InstallError]: Collecting tzlocal==2.0.0b1
> [pipenv.exceptions.InstallError]:   Using cached tzlocal-2.0.0b1-py2.py3-none-any.whl (18 kB)
> [pipenv.exceptions.InstallError]: Requirement already satisfied, skipping upgrade: umbral==0.1.3a0 in /home/nics/.local/share/virtualenvs/vehicle-data-exchange-cEJPwm8i/lib/python3.8/site-packages (from nucypher->-r /tmp/pipenv-8cpqyqws-requirements/pipenv-laa47jua-requirement.txt (line 1)) (0.1.3a0)
> [pipenv.exceptions.InstallError]: Collecting watchdog==0.9.0
> [pipenv.exceptions.InstallError]:   Using cached watchdog-0.9.0.tar.gz (85 kB)
> [pipenv.exceptions.InstallError]: Collecting web3[tester]==5.0.0a5
> [pipenv.exceptions.InstallError]:   Using cached web3-5.0.0a5-py3-none-any.whl (137 kB)
> [pipenv.exceptions.InstallError]: Collecting websockets==7.0
> [pipenv.exceptions.InstallError]:   Using cached websockets-7.0.tar.gz (49 kB)
> [pipenv.exceptions.InstallError]: Collecting werkzeug==0.14.1
> [pipenv.exceptions.InstallError]:   Using cached Werkzeug-0.14.1-py2.py3-none-any.whl (322 kB)
> [pipenv.exceptions.InstallError]: Collecting zope.interface==4.6.0
> [pipenv.exceptions.InstallError]:   Using cached zope.interface-4.6.0.tar.gz (150 kB)
> [pipenv.exceptions.InstallError]: Running command git fetch -q --tags
> [pipenv.exceptions.InstallError]:   Running command git reset --hard -q e5a187adef2611896d67ce52ec3d08685009535b
> [pipenv.exceptions.InstallError]:     ERROR: Command errored out with exit status 1:
> [pipenv.exceptions.InstallError]:      command: /home/nics/.local/share/virtualenvs/vehicle-data-exchange-cEJPwm8i/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j77czk6j/zope.interface/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j77czk6j/zope.interface/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z_8huvck
> [pipenv.exceptions.InstallError]:          cwd: /tmp/pip-install-j77czk6j/zope.interface/
> [pipenv.exceptions.InstallError]:     Complete output (5 lines):
> [pipenv.exceptions.InstallError]:     Traceback (most recent call last):
> [pipenv.exceptions.InstallError]:       File "<string>", line 1, in <module>
> [pipenv.exceptions.InstallError]:       File "/tmp/pip-install-j77czk6j/zope.interface/setup.py", line 26, in <module>
> [pipenv.exceptions.InstallError]:         from setuptools import setup, Extension, Feature
> [pipenv.exceptions.InstallError]:     ImportError: cannot import name 'Feature' from 'setuptools' (/home/nics/.local/share/virtualenvs/vehicle-data-exchange-cEJPwm8i/lib/python3.8/site-packages/setuptools/__init__.py)
> [pipenv.exceptions.InstallError]:     ----------------------------------------
> [pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Couldn't install package: nucypher
>  Package installation failed...
>   ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/3 — 00:01:08
>

**Comment by derekpierre** [comment]
This repos was originally created for the MOBI hackathon (https://devpost.com/software/obdx) and has not been maintained since.

The underlying `nucypher` network which was showcased by this demo has progressed since then. The updated documentation and associated demos can be found at https://docs.nucypher.com.
